g++ main.cpp\
 source/config.cpp\
 source/particle_emitter.cpp\
 source/pipeline.cpp\
 source/progress.cpp\
 source/program.cpp\
 source/stage.cpp\
 source/uniform_map.cpp\
 source/vector_field.cpp\
 source/vector_field_generator.cpp\
 source/viewer.cpp\
 -omain\
 -std=c++11\
 -Wall\
 -pedantic\
 -Iinclude\
 -lGLEW\
 -lglut\
 -L/usr/lib/nvidia-331\
 -lGL
